// Service worker — installability, push notifications, offline fallback.
// Bump SW_VERSION on every deploy: changing this file's bytes makes browsers
// detect a SW update, which (via the controllerchange listener in index.html)
// auto-reloads open clients onto the latest code.
const SW_VERSION = "2026-10-07-1";
const CACHE = 'ufc-' + SW_VERSION;
// Handoff caches that must survive SW upgrades: 'ufc-push-id' carries the push
// identity used by pushsubscriptionchange while the app is closed, 'ufc-tap'
// carries a pending notification-tap payload to the page it opens.
const KEEP_CACHES = ['ufc-push-id', 'ufc-tap'];

self.addEventListener('install', function(e) {
  self.skipWaiting();
  // Precache the app shell so the PWA opens offline. Each URL is cached
  // independently — one miss must not block install.
  e.waitUntil(caches.open(CACHE).then(function(c) {
    var core = ['./', './data.js', './scoring.js?v=2026-10-03-1', './lab/engine.js', './manifest.json', './icon-192-v3.png', './sounds/eagle-1.mp3', './sounds/eagle-2.mp3'];
    // Seasonal cues: precache only THIS month's file. All twelve together are
    // ~5.7MB, which is not worth forcing down every install for eleven sounds
    // nobody can reach yet — the fetch handler below already runtime-caches
    // same-origin responses, so the other months are cached the first time
    // they are played and are offline from then on. A missing file is
    // harmless: c.add() misses are swallowed and the theme falls back to its
    // synthesised cue.
    core.push('./sounds/season-' +
      ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'][new Date().getMonth()] +
      '.mp3');
    return Promise.all(core.map(function(u) {
      return c.add(u).catch(function() {});
    }));
  }));
});

self.addEventListener('activate', function(e) {
  e.waitUntil(
    caches.keys()
      .then(function(keys) {
        return Promise.all(keys.filter(function(k) { return k !== CACHE && KEEP_CACHES.indexOf(k) < 0; })
          .map(function(k) { return caches.delete(k); }));
      })
      .then(function() { return self.clients.claim(); })
  );
});

// The page and data.js are pulled fresh from the network so code/result updates
// land immediately, bypassing any stale HTTP cache (iOS PWAs cache stubbornly).
// Successful responses refresh the offline copy; when the network is down, the
// last-good copy is served instead of a white screen. Everything else
// (fonts, icons) is cache-first.
self.addEventListener('fetch', function(e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  var isNavigate = req.mode === 'navigate';
  var path = new URL(req.url).pathname;
  var isData = !isNavigate && path.slice(-8) === '/data.js';
  // intel.json joins the network-first set for the same reason data.js is in it:
  // it is regenerated by the update workflow and the cache-first branch below
  // would pin an installed PWA to whatever fight week it first saw.
  var isIntel = !isNavigate && path.slice(-11) === '/intel.json';
  // scoring.js is part of the page, not an asset: it must always match the
  // index.html it was shipped with, so it's fetched fresh like the page is.
  var isScoring = !isNavigate && path.slice(-11) === '/scoring.js';
  // The Fight Lab (lab.html) reads the same way: odds-series.json and
  // events-extra.json are regenerated/curated, lab/*.js change with the app,
  // and index.html is fetched as TEXT so the lab can lift the app's own scoring
  // out of it — a cache-first copy would score against last month's rules.
  var isLabNav = isNavigate && path.slice(-9) === '/lab.html';
  // The static pages (privacy, terms, support) are navigations too; each keeps
  // its own key, or opening one from the menu would overwrite the app shell
  // and an offline launch would open a legal page instead of the app.
  var staticNav = isNavigate && /\/(privacy|terms|support)\.html$/.exec(path);
  var labKey = !isNavigate && (
    path.slice(-17) === '/odds-series.json' ? './odds-series.json' :
    path.slice(-18) === '/events-extra.json' ? './events-extra.json' :
    path.slice(-11) === '/index.html' ? './index.html' :
    path.indexOf('/lab/') >= 0 && path.slice(-3) === '.js' ? '.' + path.slice(path.indexOf('/lab/')) : null);
  if (isNavigate || isData || isIntel || isScoring || labKey) {
    // Every navigation used to be cached under './'. With a second page that
    // would let opening the lab overwrite the app shell's offline copy, so the
    // lab keeps its own key and an offline app launch still gets the app.
    // scoring.js is keyed by its FULL versioned URL (scoring.js?v=…), so the
    // offline fallback can only ever return the version the page asked for.
    var cacheKey = isLabNav ? './lab.html' : staticNav ? '.' + staticNav[0] : isNavigate ? './' : isScoring ? req.url : labKey || (isIntel ? './intel.json' : './data.js');
    e.respondWith(
      fetch(req, { cache: 'reload' })
        .catch(function() { return fetch(req); })
        .then(function(res) {
          if (res && res.ok) {
            var copy = res.clone();
            caches.open(CACHE).then(function(c) { c.put(cacheKey, copy); });
          }
          return res;
        })
        .catch(function() {
          return caches.match(cacheKey).then(function(hit) {
            if (hit) return hit;
            throw new Error('offline and no cached copy');
          });
        })
    );
    return;
  }
  if (req.url.indexOf(self.location.origin + '/') === 0) {
    e.respondWith(
      caches.match(req).then(function(hit) {
        if (hit) return hit;
        return fetch(req).then(function(res) {
          if (res && res.ok) {
            var copy = res.clone();
            caches.open(CACHE).then(function(c) { c.put(req, copy); });
          }
          return res;
        });
      })
    );
  }
});


// Single source of truth for the app version: the page asks the controlling SW
// for SW_VERSION and renders it in the footer, so the footer can't drift from the
// real running version (and surfaces stale-cache situations at a glance).
self.addEventListener('message', function(e) {
  if (e.data && e.data.type === 'getVersion' && e.ports && e.ports[0]) {
    e.ports[0].postMessage({ type: 'version', version: SW_VERSION });
  }
});

// Base64url <-> bytes, mirroring the page helpers, so the SW can re-subscribe
// and re-register without the page being open.
function urlB64ToUint8(b64) {
  var pad = '='.repeat((4 - b64.length % 4) % 4);
  var raw = atob((b64 + pad).replace(/-/g, '+').replace(/_/g, '/'));
  var out = new Uint8Array(raw.length);
  for (var i = 0; i < raw.length; i++) out[i] = raw.charCodeAt(i);
  return out;
}
function bufToB64Url(buf) {
  var bytes = new Uint8Array(buf), s = '';
  for (var i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

// Browsers (notably Chrome/FCM) periodically rotate push subscriptions. Without
// this handler the old endpoint just dies and the user silently stops receiving
// pushes while the app is closed. Re-subscribe and re-register using the identity
// the page stashed in the 'ufc-push-id' cache.
self.addEventListener('pushsubscriptionchange', function(e) {
  e.waitUntil(
    caches.open('ufc-push-id')
      .then(function(c) { return c.match('/__push_id'); })
      .then(function(res) { return res ? res.json() : null; })
      .then(function(id) {
        if (!id || !id.vapid || !id.url) return;
        return self.registration.pushManager.subscribe({
          userVisibleOnly: true,
          applicationServerKey: urlB64ToUint8(id.vapid)
        }).then(function(sub) {
          var p256dh = sub.getKey('p256dh'), auth = sub.getKey('auth');
          if (!p256dh || !auth) return;
          return fetch(id.url + '/functions/v1/send-push', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + id.anon },
            body: JSON.stringify({
              type: 'register', user_id: id.user_id, nickname: id.nickname,
              endpoint: sub.endpoint, p256dh: bufToB64Url(p256dh), auth: bufToB64Url(auth),
              live_results: !!id.live_results
            })
          });
        });
      })
      .catch(function() {})
  );
});

var PUSH_TELL_MS = 2000;   // longest the push event waits to tell open pages
self.addEventListener('push', function(e) {
  var data = {};
  try { data = e.data ? e.data.json() : {}; } catch(err) {}

  // Full body text shown in notification — iOS collapses to ~2 lines, long-press to expand.
  // Separator \n---\n is legacy; fullMessage falls back to rawBody so in-app tap always works.
  var rawBody = data.body || '';
  var sep = rawBody.indexOf('\n---\n');
  var displayBody = sep >= 0 ? rawBody.slice(0, sep) : rawBody;
  var fullMessage = sep >= 0 ? rawBody.slice(sep + 5) : rawBody;

  // The notification goes up FIRST and unconditionally. iOS treats a push
  // that shows no notification as silent (and revokes the subscription after
  // a few), so nothing may stand in front of showNotification. #242 put a
  // clients.matchAll() ahead of it to tell open pages a push had arrived; a
  // friend's phone then got a roast Apple had accepted but showed no banner.
  // Telling the page now runs beside it, and can't delay or block it.
  var shown = self.registration.showNotification(data.title || 'Picked Fight', {
    body: displayBody,
    icon: './icon-192-v3.png',
    badge: './icon-192-v3.png',
    data: { url: data.url || './', kind: data.kind || '', fullMessage: fullMessage }
  });
  // Tell any open page a push arrived, so it reads the roast inbox right away
  // instead of relying on the tap to carry the roast in (see index.html).
  var told = Promise.resolve().then(function() {
    return clients.matchAll({ type: 'window', includeUncontrolled: true });
  }).then(function(cs) {
    cs.forEach(function(c) { try { c.postMessage({ type: 'push-arrived', kind: data.kind || '' }); } catch (err) {} });
  }).catch(function() {});
  // Bounded: a lookup that never settles must not keep the push event (and the
  // worker) alive. The banner is already up; telling the page is a bonus.
  var toldOrTimeout = Promise.race([told, new Promise(function(res) { setTimeout(res, PUSH_TELL_MS); })]);
  e.waitUntil(Promise.all([shown, toldOrTimeout]));
});

self.addEventListener('notificationclick', function(e) {
  e.notification.close();
  var fullMessage = e.notification.data && e.notification.data.fullMessage;
  var kind = (e.notification.data && e.notification.data.kind) || '';
  var baseUrl = (e.notification.data && e.notification.data.url) || './';
  // The trash-talk title is "🎤 Persona (via Sender)" — recover the sender so
  // the in-app sheet can credit who hired the voice (only the body is otherwise
  // forwarded). Best-effort: blank if the title isn't in that shape.
  var senderMatch = (e.notification.title || '').match(/\(via\s+(.+?)\)\s*$/);
  var sender = senderMatch ? senderMatch[1] : '';

  // The tap payload is handed over through the 'ufc-tap' cache, which the page
  // consumes on load: roasts can run ~1300 chars, too long to trust to a URL.
  //
  // This is written on EVERY tap, before any routing decision, because a
  // postMessage to a focused client is not a delivery guarantee — see the
  // matchAll block below. If the message lands, the live page clears the stash
  // (see the 'message' handler in index.html) so it can't resurface later; if
  // it vanished into a dead client, the relaunched page finds it and the roast
  // still shows. Cheap either way, and it removes the only path where a tap
  // could produce nothing at all.
  // One id for this tap, carried by BOTH the stash and the postMessage, so the
  // page can tell "the message and the stash are the same tap" from "two taps"
  // and show the roast exactly once when both paths deliver.
  var tapTs = Date.now();

  // Is this window on the app page itself (this worker's scope root or its
  // index.html), rather than another page of the app such as lab.html, or a
  // same-origin page outside the scope that merely ends in '/'?
  function onAppPage(c) {
    try {
      var u = new URL(c.url), root = new URL(self.registration.scope);
      return u.origin === root.origin && (u.pathname === root.pathname || u.pathname === root.pathname + 'index.html');
    } catch (err) { return false; }
  }

  function stashTap() {
    return caches.open('ufc-tap').then(function(c) {
      return c.put('/__pending_tap', new Response(
        JSON.stringify({ kind: kind, fullMessage: fullMessage, sender: sender, ts: tapTs }),
        { headers: { 'Content-Type': 'application/json' } }
      ));
    }).catch(function() {});
  }

  // App closed (or focusing failed) — open a window. The legacy ?trash= param
  // is still added when it fits, so a stale cached page paired with this SW
  // keeps working.
  function openFresh() {
    return Promise.resolve().then(function() {
      var url = baseUrl;
      if (!kind && fullMessage) {
        var enc = encodeURIComponent(fullMessage);
        if (enc.length <= 1800) {
          url += (url.indexOf('?') >= 0 ? '&' : '?') + 'trash=' + enc;
          if (sender) url += '&from=' + encodeURIComponent(sender);
        }
      }
      if (clients.openWindow) return clients.openWindow(url);
    });
  }

  // A push that links to another page (the Friday brief → lab.html#week) has
  // nothing to hand the app: no roast, no inbox. Stashing a tap for it would
  // leave an empty payload for index.html to find later, and focusing an open
  // app window without navigating would drop the user on the fight cards. So
  // navigate the open window there, or open one.
  if (/^\.\/lab\.html(#[a-z]+)?$/.test(baseUrl)) {
    e.waitUntil(clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(cs) {
      var t = cs.filter(function(c) { return 'navigate' in c && 'focus' in c; })[0];
      if (!t) return clients.openWindow && clients.openWindow(baseUrl);
      return t.focus().then(function(c) { return (c || t).navigate(baseUrl); })
        .catch(function() { return clients.openWindow && clients.openWindow(baseUrl); });
    }));
    return;
  }

  e.waitUntil(stashTap().then(function() {
    return clients.matchAll({ type: 'window', includeUncontrolled: true });
  }).then(function(cs) {
    // App is already open — focus it and route the tap by kind. Prefer a
    // visible client. Note that neither focus() resolving NOR postMessage
    // returning tells us the page actually received anything: iOS keeps
    // listing a window client for a PWA the OS already killed, focus() on it
    // resolves happily, and the message vanishes. Guarding on focus()
    // rejecting — which is what this used to do — never fires for that case,
    // so the tap silently did nothing and the app opened on the home screen.
    // stashTap() above is what makes this safe: the relaunched page picks the
    // payload up regardless of what happened to the message.
    //
    // Only the app page (index.html) can show a roast or the inbox. The Fight
    // Lab opens in the same window, so the one window a PWA has can be sitting
    // on lab.html, which has no message handler and never reads the stash: the
    // tap focused it and nothing appeared. Prefer a window on the app page;
    // if the only one is elsewhere, navigate it to the app, whose on-load
    // consumer picks the stashed tap up.
    var candidates = cs.filter(function(c) { return 'focus' in c; });
    candidates.sort(function(a, b) {
      return (onAppPage(b) ? 2 : 0) + (b.visibilityState === 'visible' ? 1 : 0)
        - (onAppPage(a) ? 2 : 0) - (a.visibilityState === 'visible' ? 1 : 0);
    });
    var target = candidates[0];
    if (!target) return openFresh();
    if (!onAppPage(target)) {
      if (!('navigate' in target)) return openFresh();
      return target.focus().then(function(c) { return (c || target).navigate(baseUrl); })
        .catch(openFresh);
    }
    // Post BEFORE focusing. The message used to wait on focus() resolving, so
    // a focus() that rejected (the app already on screen, where there is
    // nothing to bring forward) meant no message at all, and with the page
    // already visible no visibilitychange fires to read the stash either:
    // the tap did nothing. The page dedupes on tapTs, so a message that lands
    // alongside the stash still shows the roast once.
    return Promise.resolve()
      .then(function() {
        if (kind) target.postMessage({ type: kind, fullMessage: fullMessage, sender: sender, ts: tapTs });
        else if (fullMessage) target.postMessage({ type: 'trash-talk', fullMessage: fullMessage, sender: sender, ts: tapTs });
        return target.focus();
      })
      .catch(function() {
        // The message is already out. A visible window rejecting focus() is
        // the app already on screen: opening another would show the tap twice
        // or pull the user off the page. Only a hidden window, which may be a
        // client iOS already killed, falls back to a fresh one.
        if (target.visibilityState !== 'visible') return openFresh();
      });
  }));
});
