// Uses the runtime's built-in Deno.serve — no deno.land/std import, so deploys
// don't depend on deno.land being up.
// Always-on server-side fight-reminder sender.
//
// The "Main Card / Prelims starting in under 1 hour" reminders were fired by
// the web client (index.html `checkNotifSchedule`, on a 5-min setInterval). That
// only works while *someone* has the app open near event time — if every phone
// is closed an hour before the card, no reminder ever goes out. This scheduled
// function closes that gap: driven by pg_cron, it computes each upcoming event's
// start times and calls the existing `send-push`.
//
// It produces the exact same notification types the client did — `main` and
// `prelim`, keyed on the event date — so `send-push`'s `notif_log`
// (event_date, type) dedup guarantees ONE reminder per event per phase no matter
// which trigger (open client or this cron) reaches it first.
//
// Deployed with --no-verify-jwt: the Supabase gateway would otherwise reject the
// cron's `Authorization: Bearer <CRON_SECRET>` as an invalid JWT before this code
// runs. Inbound auth is enforced here via CRON_SECRET instead.

// Where to read the live event schedule. The published data.js is the same file
// the PWA loads and is regenerated by scrape.py, so it always reflects the
// current card/times. Overridable for testing.
const DATA_URL = Deno.env.get("DATA_URL") ??
  "https://andyrbrett.github.io/ufc-dashboard/data.js";

// Fire when an event phase is within this lead window and hasn't started yet
// (mirrors the client's "diff>0 && diff<=HOUR_MS" check). A small grace lets a
// cron run that lands right at start still notify; the dedup stops repeats.
const LEAD_MS = 60 * 60 * 1000;
const GRACE_MS = 2 * 60 * 1000;
const MAX_EVENTS = 8; // hard cap on events considered per run

interface Ev { name: string; date: string; time: string; prelimTime: string; }

// Eastern Time → UTC offset in hours, replicated from index.html `etOffset()`:
// UTC-4 (EDT, 2nd Sun Mar → 1st Sun Nov) else UTC-5 (EST). Event times in
// data.js are wall-clock ET, exactly as the client interprets them.
function etOffset(): number {
  const d = new Date(), y = d.getUTCFullYear();
  const s = new Date(Date.UTC(y, 2, 8));
  s.setUTCDate(8 + ((7 - s.getUTCDay()) % 7)); // 2nd Sunday March
  const e = new Date(Date.UTC(y, 10, 1));
  e.setUTCDate(1 + ((7 - e.getUTCDay()) % 7)); // 1st Sunday November
  return (d >= s && d < e) ? 4 : 5;
}

// Wall-clock ET "HH:MM" on event date → absolute UTC ms, or null for TBD/blank.
function phaseUtc(date: string, time: string): number | null {
  if (!time || time.toUpperCase() === "TBD") return null;
  const dp = date.split("-").map(Number);
  const tp = time.split(":").map(Number);
  if (dp.length !== 3 || isNaN(dp[0]) || isNaN(tp[0])) return null;
  return Date.UTC(dp[0], dp[1] - 1, dp[2], tp[0] + etOffset(), tp[1] || 0, 0);
}

// Pull name/date/time/prelimTime out of data.js's `var EVENTS=[…]`. The fight
// objects nested under each event have no `time`/`prelimTime` keys, so matching
// `time:"…",prelimTime:"…"` lands on the event header every time.
function parseEvents(js: string): Ev[] {
  const out: Ev[] = [];
  const re =
    /name:"([^"]+)",\s*date:"(\d{4}-\d{2}-\d{2})"[\s\S]*?time:"([^"]*)",\s*prelimTime:"([^"]*)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(js)) !== null) {
    out.push({ name: m[1], date: m[2], time: m[3], prelimTime: m[4] });
  }
  return out;
}

// ── Fight Week Brief ────────────────────────────────────────────────────────
// Friday 19:00 ET before each card, one push to everyone with notifications on
// (the 🔔 bell — the same audience as the reminders; no separate opt-in, by
// design). Deduped by send-push's notif_log on (event_date, "brief"), so the
// 5-minute cadence sends it once. It deep-links to the Fight Lab's Fight Week
// tab, where the full brief lives.
//
// The copy is built by the Lab's own code (lab/engine.js + lab/analytics.js,
// with the board's scoring lifted out of index.html), fetched from the same
// Pages origin as data.js — so the push can't say something the Lab doesn't.
// If any of that fails, a plain teaser still goes out: a brief that arrives
// without its headline beats no brief.
const PAGES_BASE = DATA_URL.replace(/data\.js(\?.*)?$/, "");
export const BRIEF_HOUR_ET = 19;
// GitHub's scheduler runs late (see scheduled-push.yml), so the brief may land
// any time in this window; after 23:00 ET it's a late-night buzz, not a brief.
export const BRIEF_WINDOW_MS = 4 * 60 * 60 * 1000;
export const BRIEF_URL = "./lab.html#week";

// The Friday on or before the card date (ET calendar), 19:00 ET, as UTC ms.
export function briefUtc(cardDate: string): number | null {
  const dp = cardDate.split("-").map(Number);
  if (dp.length !== 3 || dp.some(isNaN)) return null;
  const d = new Date(Date.UTC(dp[0], dp[1] - 1, dp[2]));
  const back = (d.getUTCDay() - 5 + 7) % 7;          // 5 = Friday
  d.setUTCDate(d.getUTCDate() - back);
  const fri = d.toISOString().slice(0, 10);
  return phaseUtc(fri, `${BRIEF_HOUR_ET}:00`);
}
// Due now? Inside the window, and before the card's first segment starts —
// judged at the moment of sending, not the scheduled 19:00: a late scheduler
// run inside the window must still never announce a card that has begun.
export function briefDue(ev: Ev, now: number): boolean {
  const t = briefUtc(ev.date);
  if (t === null || now < t || now >= t + BRIEF_WINDOW_MS) return false;
  const first = phaseUtc(ev.date, ev.prelimTime) ?? phaseUtc(ev.date, ev.time);
  return first === null || now < first;
}

function to12(t: string): string {
  const [h, m] = t.split(":").map(Number);
  if (isNaN(h)) return t;
  return `${((h + 11) % 12) + 1}${m ? ":" + String(m).padStart(2, "0") : ""}${h < 12 ? "am" : "pm"}`;
}
const DAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

export async function composeBrief(ev: Ev, js: string, sb: { url: string; key: string } | null, now: number):
  Promise<{ title: string; body: string; rich: boolean }> {
  const dp = ev.date.split("-").map(Number);
  const day = DAY_NAMES[new Date(Date.UTC(dp[0], dp[1] - 1, dp[2])).getUTCDay()];
  const headline = ev.name.includes(":") ? ev.name.split(":").slice(1).join(":").trim() : ev.name;
  const title = `📰 ${day} Brief: ${headline}`.slice(0, 118);
  const when = ev.time && ev.time.toUpperCase() !== "TBD" ? ` Main card ${to12(ev.time)} ET.` : "";
  const plain = { title, body: `Fight week is here.${when} Tap for the lines, the stories and the fights worth studying.`, rich: false };
  try {
    const get = async (f: string) => {
      const r = await fetch(`${PAGES_BASE}${f}?t=${now}`);
      if (!r.ok) throw new Error(`${f} HTTP ${r.status}`);
      return r.text();
    };
    const [engineJs, analyticsJs, html, scoringJs, oddsTxt, intelTxt] = await Promise.all([
      get("lab/engine.js"), get("lab/analytics.js"), get("index.html"), get("scoring.js"),
      get("odds-series.json"), get("intel.json").catch(() => "null"),
    ]);
    const root: Record<string, any> = {};
    new Function("globalThis", engineJs)(root);
    new Function("globalThis", analyticsJs)(root);
    const PE = root.PickEngine, FL = root.FightLab;
    const env = new Function(js + "\n;return {EVENTS:EVENTS,RESULTS_ARCHIVE:typeof RESULTS_ARCHIVE!=='undefined'?RESULTS_ARCHIVE:{},FIGHTER_STATS:typeof FIGHTER_STATS!=='undefined'?FIGHTER_STATS:{},RANKINGS:typeof RANKINGS!=='undefined'?RANKINGS:{}};")();
    const kernel = PE.loadKernel(html, env, undefined, scoringJs);
    const engine = PE.createEngine({ adapters: [PE.ufcAdapter(env)], rules: { ufc: PE.ufcRules(kernel) } });
    const nev = engine.events("ufc").find((e: any) => e.date === ev.date && e.name === ev.name);
    if (!nev) return plain;
    let group: any[] = [];
    if (sb) {
      try {
        const r = await fetch(`${sb.url}/rest/v1/picks?select=user_id,nickname,event_date,f1,f2,pick,method,confidence,updated_at,bonus_pick&event_date=eq.${ev.date}&promotion=eq.ufc`,
          { headers: { apikey: sb.key, Authorization: `Bearer ${sb.key}` } });
        if (r.ok) group = engine.resolvePicks(PE.boardRows(kernel, await r.json()));
      } catch (_e) { /* no group line; the rest of the brief stands */ }
    }
    const raw = env.EVENTS.find((e: any) => e.date === ev.date && e.name === ev.name);
    const intel = raw && intelTxt !== "null" ? kernel.intelItemsFor(JSON.parse(intelTxt), raw) : [];
    const edgeFor = (b: any) => b.raw && b.raw.f1 ? kernel.modelEdge(b.raw, env.FIGHTER_STATS, env.RANKINGS, env.RESULTS_ARCHIVE) : null;
    const brief = FL.fightWeekBrief(nev, { odds: FL.oddsIndex(JSON.parse(oddsTxt)), intel, group, mine: [], edgeFor, now: new Date(now) });
    // Everyone gets the same push, so the per-user "You've picked" line stays in the Lab.
    const lines: string[] = brief.items.filter((i: any) => !/^You've picked/.test(i.text)).map((i: any) => `${i.icon} ${i.text}`);
    if (brief.study.length) {
      const s = brief.study[0], c = s.bout.competitors;
      lines.push(`🔍 Worth a look: ${c[0].name} vs ${c[1].name}`);
    }
    if (!lines.length) return plain;
    // A lock screen shows a few lines, so lead with what's worth opening for:
    // the line move, the group's split, the fight to study, then the reading.
    const PRIORITY = ["📉", "🔥", "🔍", "📰", "♨️", "⏳"];
    const rank = (l: string) => { const i = PRIORITY.findIndex((p) => l.startsWith(p)); return i < 0 ? PRIORITY.length : i; };
    lines.sort((a, b) => rank(a) - rank(b));
    const body = (lines.slice(0, 4).join("\n") + (when ? "\n🕘" + when : "")).slice(0, 900);
    return { title, body, rich: true };
  } catch (e) {
    console.warn("[brief] falling back to the plain teaser:", (e as Error).message);
    return plain;
  }
}

// Constant-time comparison. `!==` on a secret returns at the first differing
// byte, so response timing across enough requests leaks the secret prefix by
// prefix. Length is still observable; that is standard and not worth hiding.
function secretEquals(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { status: 204 });
  if (req.method !== "POST" && req.method !== "GET") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405, headers: { "Content-Type": "application/json" } });
  }

  // Inbound auth: only a caller that knows CRON_SECRET may trigger this. Accept
  // it header-only: `Authorization: Bearer <secret>`. The ?key= form was removed
  // query param (so external cron UIs work without custom headers).
  // Header-only. A secret in the query string is written to every log that
  // records a URL — Supabase's own edge logs, any proxy in front of them, and
  // the Referer of anything the response links to — which a header is not.
  // scheduled-push.yml has always sent this as a header, so dropping the
  // ?key= path costs nothing here.
  const CRON_SECRET = Deno.env.get("CRON_SECRET") ?? "";
  const bearer = (req.headers.get("Authorization") ?? "").replace(/^Bearer\s+/i, "").trim();
  if (!CRON_SECRET || !secretEquals(bearer, CRON_SECRET)) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { "Content-Type": "application/json" } });
  }

  const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
  const SB_ANON_KEY = Deno.env.get("SB_ANON_KEY");
  if (!SUPABASE_URL || !SB_ANON_KEY) {
    return new Response(JSON.stringify({ error: "Server misconfigured" }), { status: 500, headers: { "Content-Type": "application/json" } });
  }
  const pushHeaders = { "Content-Type": "application/json", "Authorization": `Bearer ${SB_ANON_KEY}` };

  let js: string;
  try {
    const r = await fetch(`${DATA_URL}?t=${Date.now()}`, { headers: { "User-Agent": "UFC-Dashboard/1.0 (github.com/AndyRBrett/ufc-dashboard)" } });
    if (!r.ok) return new Response(JSON.stringify({ error: "Failed to fetch schedule", status: r.status }), { status: 502, headers: { "Content-Type": "application/json" } });
    js = await r.text();
  } catch (_e) {
    return new Response(JSON.stringify({ error: "Failed to fetch schedule" }), { status: 502, headers: { "Content-Type": "application/json" } });
  }

  const now = Date.now();
  const events = parseEvents(js)
    // Only events whose main card could still be in the lead window (today or
    // the next couple of days); keeps the per-run work tiny and bounded.
    .filter((ev) => {
      const t = phaseUtc(ev.date, ev.time) ?? phaseUtc(ev.date, ev.prelimTime);
      return t !== null && t > now - 6 * 864e5 && t < now + 3 * 864e5;
    })
    .slice(0, MAX_EVENTS);

  // Phase → push copy, byte-for-byte from index.html `checkNotifSchedule`.
  const short = (name: string) => name.split(":")[0];
  let sent = 0, fired = 0;
  const out: unknown[] = [];

  for (const ev of events) {
    const phases: [string, number | null, string, string][] = [
      ["main", phaseUtc(ev.date, ev.time),
        `🥊 ${short(ev.name)} — Main Card`, "Starting in under 1 hour. Lock in your picks!"],
      ["prelim", phaseUtc(ev.date, ev.prelimTime),
        `🥊 ${short(ev.name)} — Prelims`, "Starting in under 1 hour."],
    ];
    for (const [type, startUtc, title, body] of phases) {
      if (startUtc === null) continue;
      const delta = (startUtc as number) - now;
      if (delta > LEAD_MS || delta <= -GRACE_MS) continue; // not in the pre-start window
      fired++;
      try {
        const r = await fetch(`${SUPABASE_URL}/functions/v1/send-push`, {
          method: "POST",
          headers: pushHeaders,
          body: JSON.stringify({ event_date: ev.date, type, title, body }),
        });
        const j = await r.json().catch(() => ({}));
        if (j && typeof j.sent === "number") sent += j.sent;
        out.push({ event_date: ev.date, type, result: j });
      } catch (_e) { /* best-effort; cron retries next run, notif_log dedups */ }
    }
  }

  // The Fight Week Brief (see briefDue). At most one card is due at a time.
  let brief: unknown = null;
  const due = events.find((ev) => briefDue(ev, now));
  if (due) {
    fired++;
    const b = await composeBrief(due, js, { url: SUPABASE_URL, key: SB_ANON_KEY }, now);
    try {
      const r = await fetch(`${SUPABASE_URL}/functions/v1/send-push`, {
        method: "POST",
        headers: pushHeaders,
        body: JSON.stringify({ event_date: due.date, type: "brief", title: b.title, body: b.body, url: BRIEF_URL }),
      });
      const j = await r.json().catch(() => ({}));
      if (j && typeof j.sent === "number") sent += j.sent;
      brief = { event_date: due.date, rich: b.rich, result: j };
    } catch (_e) { /* best-effort; the next run retries and notif_log dedups */ }
  }

  return new Response(
    JSON.stringify({ events: events.length, fired, sent, reminders: out, brief }),
    { status: 200, headers: { "Content-Type": "application/json" } },
  );
});
