// Uses the runtime's built-in Deno.serve — no deno.land/std import, so deploys
// don't depend on deno.land being up.
// Always-on server-side fight-reminder sender.
//
// The "Main Card / Prelims starting in under 1 hour" reminders were fired by
// the web client (index.html `checkNotifSchedule`, on a 5-min setInterval). That
// only works while *someone* has the app open near event time — if every phone
// is closed an hour before the card, no reminder ever goes out. This scheduled
// function closes that gap: driven by pg_cron, it computes each upcoming event's
// start times and calls the existing `send-push`.
//
// It produces the exact same notification types the client did — `main` and
// `prelim`, keyed on the event date — so `send-push`'s `notif_log`
// (event_date, type) dedup guarantees ONE reminder per event per phase no matter
// which trigger (open client or this cron) reaches it first.
//
// Deployed with --no-verify-jwt: the Supabase gateway would otherwise reject the
// cron's `Authorization: Bearer <CRON_SECRET>` as an invalid JWT before this code
// runs. Inbound auth is enforced here via CRON_SECRET instead.
//
// (Redeploy trigger: 2026-06-20.)

// Where to read the live event schedule. The published data.js is the same file
// the PWA loads and is regenerated by scrape.py, so it always reflects the
// current card/times. Overridable for testing.
const DATA_URL = Deno.env.get("DATA_URL") ??
  "https://andyrbrett.github.io/ufc-dashboard/data.js";

// Fire when an event phase is within this lead window and hasn't started yet
// (mirrors the client's "diff>0 && diff<=HOUR_MS" check). A small grace lets a
// cron run that lands right at start still notify; the dedup stops repeats.
const LEAD_MS = 60 * 60 * 1000;
const GRACE_MS = 2 * 60 * 1000;
const MAX_EVENTS = 8; // hard cap on events considered per run

interface Ev { name: string; date: string; time: string; prelimTime: string; }

// Eastern Time → UTC offset in hours, replicated from index.html `etOffset()`:
// UTC-4 (EDT, 2nd Sun Mar → 1st Sun Nov) else UTC-5 (EST). Event times in
// data.js are wall-clock ET, exactly as the client interprets them.
function etOffset(): number {
  const d = new Date(), y = d.getUTCFullYear();
  const s = new Date(Date.UTC(y, 2, 8));
  s.setUTCDate(8 + ((7 - s.getUTCDay()) % 7)); // 2nd Sunday March
  const e = new Date(Date.UTC(y, 10, 1));
  e.setUTCDate(1 + ((7 - e.getUTCDay()) % 7)); // 1st Sunday November
  return (d >= s && d < e) ? 4 : 5;
}

// Wall-clock ET "HH:MM" on event date → absolute UTC ms, or null for TBD/blank.
function phaseUtc(date: string, time: string): number | null {
  if (!time || time.toUpperCase() === "TBD") return null;
  const dp = date.split("-").map(Number);
  const tp = time.split(":").map(Number);
  if (dp.length !== 3 || isNaN(dp[0]) || isNaN(tp[0])) return null;
  return Date.UTC(dp[0], dp[1] - 1, dp[2], tp[0] + etOffset(), tp[1] || 0, 0);
}

// Pull name/date/time/prelimTime out of data.js's `var EVENTS=[…]`. The fight
// objects nested under each event have no `time`/`prelimTime` keys, so matching
// `time:"…",prelimTime:"…"` lands on the event header every time.
function parseEvents(js: string): Ev[] {
  const out: Ev[] = [];
  const re =
    /name:"([^"]+)",\s*date:"(\d{4}-\d{2}-\d{2})"[\s\S]*?time:"([^"]*)",\s*prelimTime:"([^"]*)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(js)) !== null) {
    out.push({ name: m[1], date: m[2], time: m[3], prelimTime: m[4] });
  }
  return out;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { status: 204 });
  if (req.method !== "POST" && req.method !== "GET") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405, headers: { "Content-Type": "application/json" } });
  }

  // Inbound auth: only the cron (which knows CRON_SECRET) may trigger this.
  const CRON_SECRET = Deno.env.get("CRON_SECRET") ?? "";
  const auth = req.headers.get("Authorization") ?? "";
  if (!CRON_SECRET || auth !== `Bearer ${CRON_SECRET}`) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { "Content-Type": "application/json" } });
  }

  const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
  const SB_ANON_KEY = Deno.env.get("SB_ANON_KEY");
  if (!SUPABASE_URL || !SB_ANON_KEY) {
    return new Response(JSON.stringify({ error: "Server misconfigured" }), { status: 500, headers: { "Content-Type": "application/json" } });
  }
  const pushHeaders = { "Content-Type": "application/json", "Authorization": `Bearer ${SB_ANON_KEY}` };

  let js: string;
  try {
    const r = await fetch(`${DATA_URL}?t=${Date.now()}`, { headers: { "User-Agent": "UFC-Dashboard/1.0 (github.com/AndyRBrett/ufc-dashboard)" } });
    if (!r.ok) return new Response(JSON.stringify({ error: "Failed to fetch schedule", status: r.status }), { status: 502, headers: { "Content-Type": "application/json" } });
    js = await r.text();
  } catch (_e) {
    return new Response(JSON.stringify({ error: "Failed to fetch schedule" }), { status: 502, headers: { "Content-Type": "application/json" } });
  }

  const now = Date.now();
  const events = parseEvents(js)
    // Only events whose main card could still be in the lead window (today or
    // the next couple of days); keeps the per-run work tiny and bounded.
    .filter((ev) => {
      const t = phaseUtc(ev.date, ev.time) ?? phaseUtc(ev.date, ev.prelimTime);
      return t !== null && t > now - 6 * 864e5 && t < now + 3 * 864e5;
    })
    .slice(0, MAX_EVENTS);

  // Phase → push copy, byte-for-byte from index.html `checkNotifSchedule`.
  const short = (name: string) => name.split(":")[0];
  let sent = 0, fired = 0;
  const out: unknown[] = [];

  for (const ev of events) {
    const phases: [string, number | null, string, string][] = [
      ["main", phaseUtc(ev.date, ev.time),
        `🥊 ${short(ev.name)} — Main Card`, "Starting in under 1 hour. Lock in your picks!"],
      ["prelim", phaseUtc(ev.date, ev.prelimTime),
        `🥊 ${short(ev.name)} — Prelims`, "Starting in under 1 hour."],
    ];
    for (const [type, startUtc, title, body] of phases) {
      if (startUtc === null) continue;
      const delta = (startUtc as number) - now;
      if (delta > LEAD_MS || delta <= -GRACE_MS) continue; // not in the pre-start window
      fired++;
      try {
        const r = await fetch(`${SUPABASE_URL}/functions/v1/send-push`, {
          method: "POST",
          headers: pushHeaders,
          body: JSON.stringify({ event_date: ev.date, type, title, body }),
        });
        const j = await r.json().catch(() => ({}));
        if (j && typeof j.sent === "number") sent += j.sent;
        out.push({ event_date: ev.date, type, result: j });
      } catch (_e) { /* best-effort; cron retries next run, notif_log dedups */ }
    }
  }

  return new Response(
    JSON.stringify({ events: events.length, fired, sent, reminders: out }),
    { status: 200, headers: { "Content-Type": "application/json" } },
  );
});
