// Reads data.js without running it.
//
// data.js is generated by scrape.py as JavaScript (`var EVENTS=[{name:"…"}]`),
// not JSON: object keys are bare identifiers. Edge functions used to evaluate
// it with `new Function`, which runs whatever the fetched file contains inside
// an isolate holding the service-role key. This parses the literal subset
// scrape.py actually writes (and nothing more) into plain values:
//
//   file   := ( comment | "var" NAME "=" value ";"? )*
//   value  := object | array | string | number | true | false | null
//   object := "{" ( key ":" value ( "," key ":" value )* )? "}"
//   key    := identifier | string
//   string := "…" with JSON escapes, plus \' (JS allows it in "…")
//
// Anything else (a call, an operator, an unknown identifier) is a parse error,
// not a guess. check:bundle proves it equals evaluating data.js on the frozen
// fixture.
export function parseDataJs(src) {
  let i = 0;
  const n = src.length;
  const fail = (what) => { throw new Error(`data.js parse: ${what} at ${i}`); };
  const ws = () => {
    for (;;) {
      while (i < n && /\s/.test(src[i])) i++;
      if (src.startsWith("//", i)) { while (i < n && src[i] !== "\n") i++; continue; }
      if (src.startsWith("/*", i)) { const e = src.indexOf("*/", i + 2); if (e < 0) fail("unterminated comment"); i = e + 2; continue; }
      return;
    }
  };
  const ident = () => {
    const m = /^[A-Za-z_$][\w$]*/.exec(src.slice(i, i + 256));
    if (!m) fail("identifier expected");
    i += m[0].length;
    return m[0];
  };
  const str = () => {
    if (src[i] !== '"') fail("string expected");
    let out = "";
    i++;
    while (i < n) {
      const c = src[i++];
      if (c === '"') return out;
      if (c === "\n") fail("newline in string");
      if (c !== "\\") { out += c; continue; }
      const e = src[i++];
      const simple = { '"': '"', "'": "'", "\\": "\\", "/": "/", b: "\b", f: "\f", n: "\n", r: "\r", t: "\t" };
      if (e in simple) out += simple[e];
      else if (e === "u") {
        const h = src.slice(i, i + 4);
        if (!/^[0-9a-fA-F]{4}$/.test(h)) fail("bad \\u escape");
        out += String.fromCharCode(parseInt(h, 16));
        i += 4;
      } else fail("bad escape \\" + e);
    }
    fail("unterminated string");
  };
  const value = (depth) => {
    if (depth > 64) fail("nesting too deep");
    ws();
    const c = src[i];
    if (c === "{") {
      i++;
      const o = {};
      ws();
      if (src[i] === "}") { i++; return o; }
      for (;;) {
        ws();
        const k = src[i] === '"' ? str() : ident();
        ws();
        if (src[i++] !== ":") fail("':' expected");
        const v = value(depth + 1);
        Object.defineProperty(o, k, { value: v, enumerable: true, writable: true, configurable: true });
        ws();
        if (src[i] === ",") { i++; continue; }
        if (src[i] === "}") { i++; return o; }
        fail("',' or '}' expected");
      }
    }
    if (c === "[") {
      i++;
      const a = [];
      ws();
      if (src[i] === "]") { i++; return a; }
      for (;;) {
        a.push(value(depth + 1));
        ws();
        if (src[i] === ",") { i++; continue; }
        if (src[i] === "]") { i++; return a; }
        fail("',' or ']' expected");
      }
    }
    if (c === '"') return str();
    const num = /^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?/.exec(src.slice(i, i + 64));
    if (num) { i += num[0].length; return Number(num[0]); }
    for (const [w, v] of [["true", true], ["false", false], ["null", null]]) {
      if (src.startsWith(w, i) && !/[\w$]/.test(src[i + w.length] || "")) { i += w.length; return v; }
    }
    fail("value expected");
  };
  const out = {};
  for (;;) {
    ws();
    if (i >= n) return out;
    if (ident() !== "var") fail("'var' expected");
    ws();
    const name = ident();
    ws();
    if (src[i++] !== "=") fail("'=' expected");
    out[name] = value(0);
    ws();
    if (src[i] === ";") i++;
  }
}
