-- Baseline: the three tables that predate this migrations folder.
--
-- picks, push_subs and notif_log were created in the Supabase dashboard before
-- migrations were kept, and 0001 onward only alter them, so the repo could not
-- rebuild the database: no staging copy, no local stack, and nothing to show
-- the live schema had drifted from the repo (it had: 0017 was never applied).
-- This file is the live definition, read from production's catalog on
-- 2026-10-04 (columns, defaults, constraints, and the three policies no later
-- migration creates). Every statement is idempotent, so applying it to
-- production changes nothing; on an empty database it is the starting point.
-- npm run check:migrations builds the whole database from 0000 up and fails if
-- any migration can't apply to the result.
--
-- Policies later migrations own are deliberately absent: picks_select /
-- picks_select_auth (0011, then 0017) and picks_insert / picks_update (0015).
-- The triggers come from 0005, 0010 and 0014.

create table if not exists public.picks (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  user_id     text default '-',
  nickname    text default '-',
  event_date  text default '-',
  event_name  text default '-',
  f1          text default '-',
  f2          text default '-',
  pick        text default '-',
  method      text not null default '''''',   -- the live default is the two-character string '' (quotes included), kept as-is
  confidence  integer not null default 0,     -- 🔒 locks since LOCKS_START (see CLAUDE.md)
  updated_at  timestamptz default now(),
  bonus_pick  text,
  constraint nickname_length check (char_length(nickname) <= 20),
  constraint picks_user_fight_unique unique (user_id, event_date, f1, f2)
);

create table if not exists public.push_subs (
  user_id      text primary key,
  nickname     text,
  endpoint     text,
  p256dh       text,
  auth         text,
  live_results boolean not null default false   -- 0002 adds it on databases created before this file
);

create table if not exists public.notif_log (
  event_date text not null,
  type       text not null,
  sent_at    timestamptz default now(),
  primary key (event_date, type)
);

alter table public.picks     enable row level security;
alter table public.push_subs enable row level security;
alter table public.notif_log enable row level security;   -- no policies: service role only

-- You can delete your own pick (the lock trigger, 0010, still refuses one
-- whose bout has locked).
drop policy if exists picks_delete on public.picks;
create policy picks_delete on public.picks for delete to authenticated
  using ((auth.uid())::text = user_id);

-- Push subscriptions are written by send-push with the service key; a device
-- may remove its own, and nobody can read them through the API.
drop policy if exists push_subs_delete on public.push_subs;
create policy push_subs_delete on public.push_subs for delete to authenticated
  using ((auth.uid())::text = user_id);
drop policy if exists push_subs_no_select on public.push_subs;
create policy push_subs_no_select on public.push_subs for select to anon
  using (false);

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on public.picks, public.push_subs, public.notif_log
  to anon, authenticated, service_role;
